# Generated by Django 3.2.5 on 2021-07-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0003_alter_artist_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2021)),
                ('picture', models.ImageField(height_field=100, null=True, upload_to='albums', width_field=100)),
                ('ratings', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.artist')),
            ],
        ),
    ]
