# Generated by Django 3.2.5 on 2021-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=100)),
                ('stageName', models.CharField(max_length=100)),
                ('recordLabel', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('dod', models.DateField(null=True)),
                ('picture', models.ImageField(height_field=50, upload_to='', width_field=50)),
                ('ratings', models.IntegerField(default=0)),
            ],
        ),
    ]
