# Generated by Django 3.2.5 on 2021-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(height_field=50, null=True, upload_to='', width_field=50),
        ),
    ]
