# Generated by Django 3.2.5 on 2021-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='picture',
            field=models.ImageField(height_field=50, null=True, upload_to='breeds', width_field=50),
        ),
    ]
